export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  VENDOR_NOT_FOUND = 'VENDOR_NOT_FOUND',
  ASSET_NOT_FOUND = 'ASSET_NOT_FOUND',
  DEPARTMENT_NOT_FOUND = 'DEPARTMENT_NOT_FOUND',
  AUDIT_NOT_FOUND = 'AUDIT_NOT_FOUND',
  AUDIT_ASSET_NOT_FOUND = 'AUDIT_ASSET_NOT_FOUND',
  TICKET_NOT_FOUND = 'TICKET_NOT_FOUND',
  UAM_NOT_FOUND = 'UAM_NOT_FOUND',
  PRODUCT_PRESET_NOT_FOUND = 'PRODUCT_PRESET_NOT_FOUND',
  PERMISSION_DENIED = 'PERMISSION_DENIED',

  UAM_NUMBER_ALRADY_GENERATED = 'UAM_NUMBER_ALRADY_GENERATED',
  UAM_UPDATE_NOT_ALLOWED = 'UAM_UPDATE_NOT_ALLOWED',

  VISIT_NOT_FOUND = 'VISIT_NOT_FOUND',
  CHECKIN_NOT_FOUND = 'CHECKIN_NOT_FOUND',
  ALREADY_CHECKED_IN = 'ALREADY_CHECKED_IN',
  ALREADY_CHECKED_OUT = 'ALREADY_CHECKED_OUT',
}
